name: Deploy on Push

on:
  push:
    branches:
      - main  # or the branch where you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # or your preferred version

    - name: Install dependencies
      run: npm install

    - name: Build and deploy
      run: npm run deploy
